### ISSUE TITLE
liblbr error

### ISSUE THREAD

**Issue by LoneWolfHT** [An0n3m0us/Minetest-AppImages#10]
```
> ./Minetest-5.4.0-x86_64.AppImage
/tmp/.mount_MineteUoA6cO/usr/bin/minetest: error while loading shared libraries: liblber-2.4.so.2: cannot open shared object file: No such file or directory
```

OS info: 
![image](https://user-images.githubusercontent.com/28972859/224140778-eee56f0c-5eb6-4870-96d3-5c4081613c23.png)

**Comment by An0n3m0us** [comment]
Thank you; I will look into it soon!

**Comment by An0n3m0us** [comment]
After solving this particular issue locally, I've been running into another (#11) so they will both be worked on in parallel.

**Comment by An0n3m0us** [comment]
Is there any particular reason you need to use 5.4.0? It's quite old, and my later AppImages seem to have this issue solved.

**Comment by LoneWolfHT** [comment]
It's useful for testing older versions without having to recompile and switch out of irrlichtmt to irrlicht

**Comment by An0n3m0us** [comment]
Alright, I've set it up for 5.4.0. Should be working; just tested it on the latest Endeavour OS.

https://github.com/An0n3m0us/Minetest-AppImages/releases/download/5.4.0/Minetest-5.4.0-x86_64-libpatch.AppImage
