### ISSUE TITLE
Unable to run on Ubuntu 20.04 LTS, using 64 bit appimage

### ISSUE THREAD

**Issue by juozaspo** [An0n3m0us/Minetest-AppImages#2]
While trying to run MT 5.2.0 AppImage from releases page I get an error
`/tmp/.mount_MineteDt7sYG/usr/bin/minetest-x86_64.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgssapi.so.3: undefined symbol: rk_memset_s, version HEIMDAL_ROKEN_1.0`
Minetest built from source works ok. I guess AppImage is not compatible with my release version, maybe you should include the library in appimage if possible next time (it might be missing from appimage)

**Comment by An0n3m0us** [comment]
Hmm, I will check it out. It looks like all I'll have to do is add that library in.

Thanks for letting me know!

**Comment by An0n3m0us** [comment]
I've updated the AppImages for Minetest 5.2.0. If you would like to try it again; that would be helpful : )

**Comment by juozaspo** [comment]
New AppImage works :)

**Comment by An0n3m0us** [comment]
Great! Thanks for testing it!
