### ISSUE TITLE
How to create appimages from source

### ISSUE THREAD

**Issue by Lejo1** [An0n3m0us/Minetest-AppImages#3]
I wanted to create a PR to add this appimage to the official minetest gitlab_ci.
How do you create the final appimages from the template?
Which tool do you use?

Thanks for your help!

PS: Do you have the source files Calinou? They aren't available anymore.

**Comment by An0n3m0us** [comment]
How I'd love to do this myself if only I had the time and knowledge :/

I create the Appimages by simply building MT and then moving the files into the correct locations.
For the source files I only used the libraries that Calinou has collected.
They can be found here:
https://github.com/An0n3m0us/Minetest-AppImages/tree/master/minetest-5.4.0-dev-i386/usr/lib
https://github.com/An0n3m0us/Minetest-AppImages/tree/master/minetest-5.4.0-dev-x86_64/usr/lib

The tool I use to package the Appimages is this one:
https://github.com/AppImage/AppImageKit/releases

**Comment by Lejo1** [comment]
Thanks first for your quick answere!

Do you build minetest as RUN_IN_PLACE=TRUE or with other cmake options?

**Comment by An0n3m0us** [comment]
This is the command I run:
`cmake . -DRUN_IN_PLACE=FALSE -DBUILD_SERVER=TRUE && make -j8`

**Comment by Lejo1** [comment]
Thanks again!
I think I now got my first version working.

Your file also contained a locale folder where have you got this from? Is it needed?

**Comment by An0n3m0us** [comment]
Neat!

Locale folder I also get from the build. Everything except the libraries are from the build, and yes, they are probably outdated xD
Sometimes I remember to update it, other times not.

But the reason why I don't update it is for backwards compatibility with Ubuntu 14.04 and older versions of the other distributions... although Ubuntu 14.04 is long gone now xD

**Comment by Lejo1** [comment]
Hmm, strange locale seems to be build in windows only. Will just pull them from there.
I'm currently thinking about using [appimage-builder](https://appimage-builder.readthedocs.io/en/latest/intro/when_to_use.html)
It would bundle all these library so they are always up to date.
Maybe that's a more productive way to do that.
