### ISSUE TITLE
No mods or texturepacks

### ISSUE THREAD

**Issue by Ygarr** [An0n3m0us/Minetest-AppImages#6]
![image](https://user-images.githubusercontent.com/14309871/141444476-8862d3c4-0f9a-4ebd-a8f5-e663b30fb386.png)

**Comment by An0n3m0us** [comment]
I believe this is an error that is not related to the AppImages but instead Minetest itself

**Comment by An0n3m0us** [comment]
Can confirm this still occurs on my system. @Ygarr I would appreciate if you could test on your system, if possible?

**Comment by Ygarr** [comment]
> 
Ok, what to do? I am usually using Manjaro. But also can run Ubuntu from portable disk. 
(My default minetest I  built and usually run from folder)

**Comment by An0n3m0us** [comment]
You can use either Manjaro or Ubuntu or any other distribution, as long as it's a fresh Minetest installation/build (and preferably 5.4.0+)
I still think this is a Minetest issue, but I don't know why they have not noticed . . .

**Comment by Ygarr** [comment]
Just run on my main system fresh(from yesterday) Appimage build, but no changes
![mineteset_issue_2022-01-16_15-57](https://user-images.githubusercontent.com/14309871/149663115-009e3824-c761-4c56-a599-3ce96dabecbf.png)

**Comment by An0n3m0us** [comment]
Thank you for testing :slightly_smiling_face:
I thought so; it must be a Minetest problem, but I wonder if they know yet.
I get this output:
```
ERROR[Main]: HTTPFetch for https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=40&engine_version=5.5.0-dev&hide=nonfree&hide=desktop_default failed (Peer certificate cannot be authenticated with given CA certificates)
ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): builtin/mainmenu/dlg_contentstore.lua:638: attempt to index field 'aliases' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	builtin/mainmenu/dlg_contentstore.lua:638: in function 'update_paths'
ERROR[Main]: 	builtin/mainmenu/dlg_contentstore.lua:1045: in function 'create_store_dlg'
ERROR[Main]: 	builtin/mainmenu/tab_content.lua:172: in function 'handle_buttons'
ERROR[Main]: 	builtin/fstk/ui.lua:142: in function 'handle_buttons'
ERROR[Main]: 	builtin/fstk/ui.lua:186: in function <builtin/fstk/ui.lua:172>
```

**Comment by An0n3m0us** [comment]
Closed as not related to the Appimages

**Comment by Ygarr** [comment]
Just tested this same Apimage on my ubuntu, and everrything is working. BUT I have installed minetest via repository 
minetest/focal,now 5.1.1+repack-1build1 amd64 [installed]
  Multiplayer infinite-world block sandbox

minetest-data/focal,focal,now 5.1.1+repack-1build1 all [installed,automatic]
  Multiplayer infinite-world block sandbox (data files)
![2022-01-17-042631_1315x625_scrot](https://user-images.githubusercontent.com/14309871/149696947-e2df3d03-d4c8-4d5a-bd6f-2fb192b07bf4.png)

**Comment by Ygarr** [comment]
Now after uninstalling "apt remove minetest" I got variable result one(no package can be retreived) after other(got list of mod/games/texturepacks stuff - ok). Looks like floating bug.

P.S. After every restart of Appimage I need to create new rule for my opensnitch firewall for Minetest to access content.minetest.net like it is new application

**Comment by An0n3m0us** [comment]
Thank you for testing this further.
Hmmm, interesting. So you think it is to do with my AppImages? If so, I'll re-open this issue.
I'm not really sure how I'm going to address this issue, but I'll also test the things you did.

**Comment by An0n3m0us** [comment]
I think I've solved it, but I just need to integrate it into the AppImage now and try it to make sure it really solves this issue.

**Comment by Ygarr** [comment]
Now thinking what package install in Manjaro. Appimage still not working and
```
core/ca-certificates 20210603-1 [installed]
    Common CA certificates (default providers)
core/ca-certificates-mozilla 3.73.1-1 [installed]
    Mozilla's set of trusted CA certificates
core/ca-certificates-utils 20210603-1 [installed]
    Common CA certificates (utilities)
core/libksba 1.6.0-1 [installed]
    Library for working with X.509 certificates, CMS data and related objects
```

**Comment by An0n3m0us** [comment]
Hmm, yeah, I get the same issue. Still trying to work it out.

**Comment by An0n3m0us** [comment]
I believe it has been fixed now. I tried my AppImages (5.5.1 and 5.6.0-dev) on the latest Manjaro and the online content menu worked fine.

**Comment by jas-framework** [comment]
Unfortunately the issue has not been fixed. I'm having this issue on the snap package as well so I don't think its your appImage.
Is there a dir where I can manually add games/mods?

**Comment by An0n3m0us** [comment]
Hmm, I see. I'll see if I can ask some devs.

Yes, `/home/$USER/.minetest/mods` and `/home/$USER/.minetest/games`.

**Comment by jas-framework** [comment]
Operating System: Parrot OS 5.0 (Electro Ara)
Kernel: Linux 5.16.0-12parrot1-amd64
Architecture: x86-64
__
@An0n3m0us

**Comment by An0n3m0us** [comment]
Thank you; I will try it when I have time.

**Comment by An0n3m0us** [comment]
Tested; it indeed occurs. I will try to address this when I have more time.

**Comment by hunter2k01** [comment]
First of all thank you very much for the AppImage, its been really helpful on Debian/Devuan where the backport version of Minetest is still on 5.4.x. However, I'm having this same issue on Devuan Stable where "No packages could be retrieved" is displayed. The output is the same as @Ygarr pointed out:

`2023-04-16 17:48:40: ERROR[Main]: HTTPFetch for https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=42&engine_version=5.7.0&hide=nonfree&hide=desktop_default failed (Peer certificate cannot be authenticated with given CA certificates)
`
This URL loads fine in a web browser and I have `ca-certificates` installed.

**Comment by An0n3m0us** [comment]
You're welcome!
Yes, unfortunately so far I have not figured out a solution, despite trying out a range of things. I've yet to work out why this error is occurring, but I think it may be related to my docker environment where I'm building the AppImage.
For me it happens even when I've built Minetest and not packaged it (i.e running it directly after building). Is that the same for you?

**Comment by hunter2k01** [comment]
Hi again and sorry for the late reply,

I just built Minetest 5.7.0 from source on Devuan and I can confirm that the content manager loads fine. I only used -DFLAG_RUN_IN_PLACE=FALSE .
![scot1](https://user-images.githubusercontent.com/96852907/236691731-9eca3da5-fc07-4d38-a443-804e412fef64.png)

**Comment by An0n3m0us** [comment]
This confirms my findings too. That's helpful! Thank you :)
I need to upgrade the environment I'm using to build the AppImages.

**Comment by An0n3m0us** [comment]
Okay, so I updated my environment and there were no changes, so then I realized this is to do with how I package the AppImage. So I need to look into that next.

**Comment by An0n3m0us** [comment]
I think I've fixed it. Can you try with this?:
https://github.com/An0n3m0us/Minetest-AppImages/releases/tag/5.7.0
Minetest-5.7.0-x86_64.AppImage

**Comment by An0n3m0us** [comment]
Tested myself and seems to work. Please re-open if it occurs again.
