### ISSUE TITLE
libpng error

### ISSUE THREAD

**Issue by gsantner** [An0n3m0us/Minetest-AppImages#9]
Hello, since the last version there is a issue with this appimage, the UI mode doesn't start anymore.

```
/tmp/.mount_minetebqBoL1/usr/bin/minetest: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

OS: Debian 11

Guess you already noticed and works at next version by <https://github.com/An0n3m0us/Minetest-AppImages/commit/bf21eaa3b7c646d3b1b1de2cee813d9c473b3a54>?

**Comment by An0n3m0us** [comment]
Hi there! Yes, I noticed and I recently fixed this. I was really busy so I could not find time to test the AppImage except on my own system after building it. Sorry about that!

**Comment by An0n3m0us** [comment]
Also, thank you for testing the AppImage and reporting the issue! I'll leave this open in case there is still another error.
